### ISSUE TITLE
Missing field is_sponsored in updateNewChat

### ISSUE THREAD

**Issue by edantie** [fewensa/telegram-client#12]
2020-05-21 07:12:09,656 ERROR [telegram_client::handler] TELEGRAM DATA FAIL. IF YOU SEE THIS MESSAGE, PLEASE POST AN ISSUE TO https://github.com/fewensa/telegram-client/issues 
 INCLUDE THIS JSON => {"@type":"updateNewChat","chat":{"@type":"chat","id":-1001003885527,"type":{"@type":"chatTypeSupergroup","supergroup_id":1003885527,"is_channel":true},"title":"La Maison des Livres Fran\u00e7ais ( livre, comic, magazine)","photo":{"@type":"chatPhoto","small":{"@type":"file","id":1,"size":0,"expected_size":0,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AQADBAAT7OD5GQAEAgADKdyE7xb___8M4Wquk1AQlGoRBAABGQQ","unique_id":"AQAD7OD5GQAEahEEAAE","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":0}},"big":{"@type":"file","id":2,"size":0,"expected_size":0,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AQADBAAT7OD5GQAEAwADKdyE7xb___8M4Wquk1AQlGwRBAABGQQ","unique_id":"AQAD7OD5GQAEbBEEAAE","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":0}}},"permissions":{"@type":"chatPermissions","can_send_messages":false,"can_send_media_messages":false,"can_send_polls":false,"can_send_other_messages":false,"can_add_web_page_previews":false,"can_change_info":false,"can_invite_users":false,"can_pin_messages":false},"order":"0","is_pinned":false,"is_marked_as_unread":false,"has_scheduled_messages":false,"can_be_deleted_only_for_self":false,"can_be_deleted_for_all_users":false,"can_be_reported":true,"default_disable_notification":false,"unread_count":80,"last_read_inbox_message_id":44707086336,"last_read_outbox_message_id":2251799812636672,"unread_mention_count":0,"notification_settings":{"@type":"chatNotificationSettings","use_default_mute_for":false,"mute_for":557442118,"use_default_sound":true,"sound":"default","use_default_show_preview":false,"show_preview":true,"use_default_disable_pinned_message_notifications":true,"disable_pinned_message_notifications":false,"use_default_disable_mention_notifications":true,"disable_mention_notifications":false},"pinned_message_id":40142635008,"reply_markup_message_id":0,"client_data":""}}
SerdeJson(Error("missing field `is_sponsored`", line: 1, column: 2295))

**Comment by fewensa** [comment]
Hi, thanks for report this issue.
What version of `tdlibjson` and `telegram-client` use?

**Comment by edantie** [comment]
With telegram-client and tdlibjson 0.*, still happening;

2020-05-21 19:22:29,741 ERROR [telegram_client::handler] TELEGRAM DATA FAIL. IF YOU SEE THIS MESSAGE, PLEASE POST AN ISSUE TO https://github.com/fewensa/telegram-client/issues 
 INCLUDE THIS JSON => {"@type":"updateNewChat","chat":{"@type":"chat","id":-178203157,"type":{"@type":"chatTypeBasicGroup","basic_group_id":178203157},"title":"Foro Oficial Anavre Canarias","photo":{"@type":"chatPhoto","small":{"@type":"file","id":19,"size":0,"expected_size":0,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AQADBAATLdxlGQAEAgAD69Vg9f____8ACAWhAgABGQQ","unique_id":"AQADLdxlGQAEBaECAAE","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":0}},"big":{"@type":"file","id":20,"size":0,"expected_size":0,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AQADBAATLdxlGQAEAwAD69Vg9f____8ACAehAgABGQQ","unique_id":"AQADLdxlGQAEB6ECAAE","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":0}}},"permissions":{"@type":"chatPermissions","can_send_messages":true,"can_send_media_messages":true,"can_send_polls":true,"can_send_other_messages":true,"can_add_web_page_previews":true,"can_change_info":false,"can_invite_users":false,"can_pin_messages":false},"order":"0","is_pinned":false,"is_marked_as_unread":false,"has_scheduled_messages":false,"can_be_deleted_only_for_self":false,"can_be_deleted_for_all_users":false,"can_be_reported":false,"default_disable_notification":false,"unread_count":1,"last_read_inbox_message_id":14996733952,"last_read_outbox_message_id":14880342016,"unread_mention_count":0,"notification_settings":{"@type":"chatNotificationSettings","use_default_mute_for":false,"mute_for":557398298,"use_default_sound":true,"sound":"default","use_default_show_preview":false,"show_preview":true,"use_default_disable_pinned_message_notifications":true,"disable_pinned_message_notifications":false,"use_default_disable_mention_notifications":true,"disable_mention_notifications":false},"pinned_message_id":0,"reply_markup_message_id":0,"client_data":""}}
SerdeJson(Error("missing field `is_sponsored`", line: 1, column: 2207))

**Comment by edantie** [comment]
You're right I'm using tdlib compiled from git.

**Comment by fewensa** [comment]
Will be fix by #14
