### ISSUE TITLE
Missing updateDiceEmojis handler

### ISSUE THREAD

**Issue by edantie** [fewensa/telegram-client#13]
2020-05-21 07:17:06,657 INFO  [telegram_client::api] <=== {"@type":"updateDiceEmojis","emojis":["\ud83c\udfb2","\ud83c\udfaf","\ud83c\udfc0"]}
2020-05-21 07:17:06,657 WARN  [telegram_client::handler] NOT HAVE [updateDiceEmojis] LISTENER, PLEASE POST AN ISSUE TO https://github.com/fewensa/telegram-client/issues , OR YOU CAN USE `on_receive` TO HANDLE THIS EVENT.

**Comment by fewensa** [comment]
I think may you use the last master branch code of [td](https://github.com/tdlib/td), And use `0.*` version of `telegram-client`.

Yes , `0.*` is flow [td](https://github.com/tdlib/td) master branch. but now it not real time. so, I checked it.

The `updateDiceEmojis` is updated there https://github.com/tdlib/td/commit/fc3a8105a3d24aefff5afcf9072312759f44663b

but now telegram-client not have include this commit. so now, you can see that error.
A stable distribution is recommended.  https://github.com/tdlib/td/releases  and this crate version is flow td, so if you use tdlibjson 1.6, this create use 1.6.*

**Comment by fewensa** [comment]
Now not have plan to update this crate flow td master version in real time. so, the 0.* version of this crate is dangers.

**Comment by fewensa** [comment]
And I think, the issue #12  is the same question.

**Comment by edantie** [comment]
I'm using 1.6.*, will switch to 0.* and test it.

**Comment by edantie** [comment]
Doesn't seem to happen with 0.*
Sorry for the noise.

**Comment by fewensa** [comment]
You can still use 1.6, and the tdlibjson also use [1.6.0](https://github.com/tdlib/td/releases/tag/v1.6.0).

**Comment by fewensa** [comment]
Will be fix by #14
