### ISSUE TITLE
Getting results for requests (getChatHistory)

### ISSUE THREAD

**Issue by joarfish** [fewensa/telegram-client#14]
Hello, thanks for your work on this. Most of it has been working splendidly for me. However, I have a problem with getting the result to `getChatHistory`. I call it like this for some chat id:
```
api.get_chat_history(
    GetChatHistory::builder()
        .chat_id(some_chat_id)
        .offset(0)
        .from_message_id(some_message_id)
        .limit(50)
        .only_local(true)
        .build()
    );
```
And I can see from the logs that tdlib is dealing properly with the request:
```
[ 3][t 4][...][Td.cpp:3592][#1][!Td][&td_requests]	Receive request 4: getChatHistory {
  chat_id = <some_chat_id>
  from_message_id = <some_message_id>
  offset = 0
  limit = 50
  only_local = true
}
...
[ 3][t 4][...][Td.cpp:4722][#1][!Td][&td_requests]	Sending result for request 4: messages {
  total_count = 50
  messages = vector[50] {
  ...
```

But where can I get this result within my application using telegram_client? Nothing is coming through via my callback to`listener.on_receive(...)`. 

I'm not sure if this is a problem with your library, with tdlib or with the way I use it. So, I hope you might be able to clarify this question.

**Comment by fewensa** [comment]
Hi, maybe the `getChatHistory` is block api, and now, I don't known what's api is block or async. so now, all api is thought async, call `api.send`.
If `getChatHistory` will block and return some data, now, you can use


```rust
let result: RTDResult<Option<String>> = api.execute(
  GetChatHistory::builder()
        .chat_id(some_chat_id)
        .offset(0)
        .from_message_id(some_message_id)
        .limit(50)
        .only_local(true)
        .build()
);
```

If we know all the methods of block api, the best way is telegram_client api fix this.

Please let me know if there are any results

**Comment by joarfish** [comment]
I tried what you suggested and this was the result I got:
```{"@type":"error","code":400,"message":"Function can't be executed synchronously"}```
So, GetChatHistory is not blocking. Do you have any other idea?

**Comment by joarfish** [comment]
This issue seems to hold more generally for all methods that have some return value (e.g. `getChats`).

**Comment by fewensa** [comment]
Yes, I think so, I will do some test, and if you have any idea please let me known. thanks.

**Comment by joarfish** [comment]
Here is an idea: I looked into `rtd.rs` at what is returned by `api.receive` (l. 21). Here we do get the response to `GetChatHistory` but there is no handler for it. So, it seems we just need to introduce handlers for types `"messages"`, `"chats"` and so on.

**Comment by joarfish** [comment]
I had a look at your `rtdlib` repo. There the required types for the missing handlers are already there. I did a quick test by adding the missing handler for type `"messages"` and it works. If you want, I could write the missing handlers and open a PR. Or is telegram-client auto-generated somehow as well?

**Comment by fewensa** [comment]
Yeah, the `telegram-client` and `rtdlib` are generated by [fantasy](https://github.com/fewensa/fantasy).
Well maybe you can create a PR to  pr branch. and then I will update fantasy project. or you can update fantasy.
I will update it as soon as you submit it, thank you for your help!

**Comment by joarfish** [comment]
I created a first attempt. Have a look and tell me, if this works for you or what I can improve.

**Comment by fewensa** [comment]
Hi, I merged your code, and I think all `Update` listener name use `on_update_*` e.g. `on_update_file` => `UpdateFile`.
All of function listener use origin name, like `on_file` => `File`

If do that, will not be compatible with previous versions. What do you think?

**Comment by fewensa** [comment]
Hi, I create pushed the new version, you can try use master branch. different versions will be released later

**Comment by joarfish** [comment]
> Hi, I merged your code, and I think all `Update` listener name use `on_update_*` e.g. `on_update_file` => `UpdateFile`.
> All of function listener use origin name, like `on_file` => `File`
> 
> If do that, will not be compatible with previous versions. What do you think?

You are right I didn't think about that to be honest. Yet, I think it might be clearer this way. I'm not sure - you might be in a better position to decide this.

**Comment by joarfish** [comment]
I checked the code you committed here and to `rtdlib`. Is this really generated by the current `fantasy` with my changes? Because I actually prefixed all event handlers for return types with `result_`. So the result to `GetChatHistory` can be captured with registering a callback to `listener.on_result_messages`.

**Comment by fewensa** [comment]
> 
> 
> I checked the code you committed here and to `rtdlib`. Is this really generated by the current `fantasy` with my changes? Because I actually prefixed all event handlers for return types with `result_`. So the result to `GetChatHistory` can be captured with registering a callback to `listener.on_result_messages`.

Yes, but have some different, All `Update` listener use `on_update_*` and all `Function` listener use `on_*` not use `on_result_*`

This modification is to make the method name and the name returned by td the same, including the modification of `on_update_*` is also the reason

https://github.com/fewensa/telegram-client/blob/4c3940d5b7843e0ec3091329d7b8fda008142763/src/listener.rs#L1178-L1182

https://github.com/fewensa/fantasy/blob/7b684e489b6ebf0e0855380217edfcfddebe9a1d/template/telegram-client/src/listener.rs#L64-L72

```rust
{% for token in tokens %}{% if token.is_return_type %}
  /// {{token.description}}
  pub fn on_{{token.name | to_snake}}<F>(&mut self, fnc: F) -> &mut Self
    where F: Fn((&Api, &{{token.name | to_camel}})) -> TGResult<()> + Send + Sync + 'static {
    self.{{token.name | to_snake}} = Some(Arc::new(fnc));
    self
  }
{% endif %}{% endfor %}
}
```

https://github.com/fewensa/fantasy/commit/3e6b86744f29c05aab6442197ab8cd6c12e5692b

So, the result to `GetChatHistory` need use `listener.on_messages`.

There have a simple changelog https://github.com/fewensa/telegram-client/blob/master/CHANGELOG.md#202005



> ## 2020/05
> 
> ### Incompatible upgrade
> 
> If you use
> 
> - `<0.6.1`
> - `<1.6.1`
> - `<1.5.1`
> - `<1.4.2`
> - `<1.3.2`
> 
> Can't directly upgrade to the next version, some api changed.
> All of `update` listener name change to `on_update_*`

The other version will be released later, now only master branch have this change.

**Comment by joarfish** [comment]
Sorry, I didn't see your commit on top of the merge commit. Now everything is clear. Thank you!

**Comment by fewensa** [comment]
All of version updated, and publish to crates.io.
Thanks for your help
