### ISSUE TITLE
Use Semver for cargo dependencies

### ISSUE THREAD

**Issue by 0xpr03** [fewensa/telegram-client#2]
Hi, is there a reason not to use [semver](https://semver.org/) compatible version declarations ?
For example `serde="1"` over `serde="1.0.91"` as per semver no breaking change in the same major version is allowed.

**Comment by fewensa** [comment]
Thanks, the next commit i will change it, but not all, only fast update dependency, like `serde` `slog`

**Comment by fewensa** [comment]
https://github.com/fewensa/telegram-client/commit/e9c67c50c0b2fa243e24a626b17760c2c5c54ac4

https://github.com/fewensa/telegram-client/commit/e71172f42463fd7d97647b10dbd8299ccafa7bfa
