### ISSUE TITLE
can't deserialize to updateSupergroupFullInfo

### ISSUE THREAD

**Issue by hh-h** [fewensa/telegram-client#24]
```
2021-05-09 21:44:38,446 ERROR [telegram_client::handler] TELEGRAM DATA FAIL. IF YOU SEE THIS MESSAGE, PLEASE POST AN ISSUE TO https://github.com/fewensa/telegram-client/issues
 INCLUDE THIS JSON => {"@type":"updateSupergroupFullInfo","supergroup_id":1345338250,"supergroup_full_info":{"@type":"supergroupFullInfo","photo":{"@type":"chatPhoto","id":"5301143349245358934","added_date":1613927407,"minithumbnail":{"@type":"minithumbnail","width":40,"height":40,"data":"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDACgcHiMeGSgjISMtKygwPGRBPDc3PHtYXUlkkYCZlo+AjIqgtObDoKrarYqMyP/L2u71////m8H////6/+b9//j/2wBDASstLTw1PHZBQXb4pYyl+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj/wAARCAAoACgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDXkkWJC7nCjqazTqDzMRH8iYOPXp1qLVp2ecQrnanJx61TjdkOV9CPzoGtzS+1FDk7jkn7zkUn9pMjAlQU7jdk1VnnEoUgEHJJH1qsSTTTXYJR63OkhlSaMPGcqaKx9LnMVyIyflk4/HtRSER3EpivrjIyScdelNFzz9zHI74qfWIDHOJ1HyvwT6GqPDgEcN3z3oAmExGOTjgff9wf6U77Ths7MnOcBuOlV9jccDnpzS8R85y3t2oAljlMlzbgDBVgOvXkUVLpMBluvNI+WPnPqaKANuSNJYyjqGU9Qax59LmiJMGJIz/CetFFAFb7PPnH2R8/Q1Yg0y4mI84+VH6d/wAqKKANiGFIIxHGuFFFFFAH/9k="},"sizes":[{"@type":"photoSize","type":"a","photo":{"@type":"file","id":1407,"size":10470,"expected_size":10470,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AgACAgIAAxUAAWCYV8b1oG10oayy1_LlKow-EZRWAAJWszEbynGRSdHQ9eBFDitRSGoAAZ8uAAMBAAMCAANhAAM0MQACHwQ","unique_id":"AQADSGoAAZ8uAAM0MQAC","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":10470}},"width":160,"height":160,"progressive_sizes":[]},{"@type":"photoSize","type":"b","photo":{"@type":"file","id":1408,"size":28099,"expected_size":28099,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AgACAgIAAxUAAWCYV8b1oG10oayy1_LlKow-EZRWAAJWszEbynGRSdHQ9eBFDitRSGoAAZ8uAAMBAAMCAANiAAM1MQACHwQ","unique_id":"AQADSGoAAZ8uAAM1MQAC","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":28099}},"width":320,"height":320,"progressive_sizes":[]},{"@type":"photoSize","type":"c","photo":{"@type":"file","id":1409,"size":70772,"expected_size":70772,"local":{"@type":"localFile","path":"","can_be_downloaded":true,"can_be_deleted":false,"is_downloading_active":false,"is_downloading_completed":false,"download_offset":0,"downloaded_prefix_size":0,"downloaded_size":0},"remote":{"@type":"remoteFile","id":"AgACAgIAAxUAAWCYV8b1oG10oayy1_LlKow-EZRWAAJWszEbynGRSdHQ9eBFDitRSGoAAZ8uAAMBAAMCAANjAAM2MQACHwQ","unique_id":"AQADSGoAAZ8uAAM2MQAC","is_uploading_active":false,"is_uploading_completed":true,"uploaded_size":70772}},"width":640,"height":640,"progressive_sizes":[]}]},"description":"\u0420\u0430\u0437\u0431\u043e\u0440\u044b \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0439 \u0421\u0428\u0410, \u0420\u043e\u0441\u0441\u0438\u0438 \u0438 \u0413\u0435\u0440\u043c\u0430\u043d\u0438\u0438.\n\u0418\u043d\u0432\u0435\u0441\u0442 \u0438\u0434\u0435\u0438 \n\n\u0412\u0442\u043e\u0440\u043e\u0439 \u043a\u0430\u043d\u0430\u043b - @AnalyticsUSARussiaMarkets\n\u0422\u0440\u0435\u0442\u0438\u0439 \u043a\u0430\u043d\u0430\u043b https://t.me/infousamarket\n\u0414\u043b\u044f \u0441\u0432\u044f\u0437\u0438 (@AnthemSky)\n\n\u041f\u043e\u0434\u0434\u0435\u0440\u0436\u0430\u0442\u044c \u043a\u0430\u043d\u0430\u043b\n4276 5215 3345 8927","member_count":60718,"administrator_count":0,"restricted_count":0,"banned_count":0,"linked_chat_id":0,"slow_mode_delay":0,"slow_mode_delay_expires_in":0.000000,"can_get_members":false,"can_set_username":false,"can_set_sticker_set":false,"can_set_location":false,"can_get_statistics":false,"is_all_history_available":true,"sticker_set_id":"0","upgraded_from_basic_group_id":0,"upgraded_from_max_message_id":0}}
2021-05-09 21:44:38,447 ERROR [telegram_client::handler] SerdeJson(Error("unknown field `\"{} can\'t deserialize to {}::{}\", updateSupergroupFullInfo, TdType,\nUpdateSupergroupFullInfo, _e`, expected `\"{:?}\", _e`", line: 0, column: 0))
```
name = "telegram-client"
version = "1.7.0"

name = "rtdlib"
version = "1.7.0"

libtdjson.so.1.7.4

I did a little investigation, it looks that `ChatPhoto.id` is a string, not an int, and `SupergroupFullInfo.invite_link` is an optional field.

**Comment by fewensa** [comment]
Hi:

libtdjson.so.1.7.4 is compiled by [tdlib/td](https://github.com/tdlib/td) master branch? You should be know, the td repository is update very fast, in this crate, the special version is follow td release version, so you can compile it use https://github.com/tdlib/td/releases/tag/v1.7.0

I will investigate all released versions in the near future.

**Comment by hh-h** [comment]
Yes, it is compiled from master, I followed the [build](https://tdlib.github.io/td/build.html) process. I thought that the patch version should not have these kinds of errors. Thanks.

**Comment by fewensa** [comment]
You can try it compile use release page, I have the same problem before, this is the [issue](https://github.com/tdlib/td/issues/1419) I submitted.
If you have any questions, post to this issue

**Comment by hh-h** [comment]
Actually, I just fixed it in the library, just posted because the console asked me to do that :)  
Although, I don't follow versioning. You have 1d7x branch and 1.7.0 tag, but https://github.com/tdlib/td has only the master branch (with version 1.7.4) and tag 1.7.0. What should I do if I want (hypothetically) a feature from the 1.7.3 version of `td`?

**Comment by fewensa** [comment]
because in td library , 1.7.3 or 1.7.4 or 1.7.x is not release version, so in telegram-client also not support release version. if you want use it, have two ways.

1. this create master branch is follow td master branch, in future may automatic compile every day to follow td master version. (not support now) the version is `0.7.x`
   you can watch those reposity
   - https://github.com/fewensa/tdlib-builder
   - https://github.com/fewensa/fantasy
   - https://github.com/fewensa/telegram-client
   - https://github.com/fewensa/rtdlib
2. manually compile yourself use [fantasy](https://github.com/fewensa/fantasy) to generate telegram-client and rtdlib create.
   Steps:
   1. Add `1.7.3` `td_api.tl` to this folder https://github.com/fewensa/fantasy/blob/master/schema
   2. Change this line use `1.7.3` file https://github.com/fewensa/fantasy/blob/7013a4013e79a9ddf02cef2c530aaf1f5936ed5e/fantasy/src/main.rs#L43
   3. run fantasy project to generate code

**Comment by caxerx** [comment]
I think td_api.tl does not update on master branch. The type of ChatPhoto.id is still int64 in the file. However, it is actually a string in the update. 
Also, in 1.7.4, the value in optionValueInteger is a string too.

**Comment by fewensa** [comment]
@caxerx Yes, you are right, the master branch is not update now, these issues will be fixed as soon

**Comment by fewensa** [comment]
Please use same version tdjson/rtdlib/telegram-client
follow this issue: https://github.com/tdlib/td/issues/1419

about your question, you can change `libtdjson.so.1.7.4` to `libtdjson.so.1.7.0`

**Comment by fewensa** [comment]
I encountered the same error, maybe this is a problem that only appeared from 1.7.0, you are right. This problem will be released in the next version .

**Comment by fewensa** [comment]
The new version released https://crates.io/crates/telegram-client
