### ISSUE TITLE
error : TELEGRAM DATA FAIL and missing field updateGroupCall

### ISSUE THREAD

**Issue by ehsansafari** [fewensa/telegram-client#28]
There is always this error ...
**ERROR [telegram_client::handler] SerdeJson(Error("missing field updateGroupCall", line: 0, column: 0))**
**ERROR [telegram_client::handler] TELEGRAM DATA FAIL. IF YOU SEE THIS MESSAGE, PLEASE POST AN ISSUE TO issues**

**Comment by fewensa** [comment]
What are versions of your use?

- tdjson (get from https://github.com/tdlib/td/releases)
- rtdlib
- telegram-client

Please use the same version, follow this [document](https://github.com/fewensa/telegram-client#version)

**Comment by ehsansafari** [comment]
_oh!, I use :_
- telegram-client = 1.7.1
- rtdlib = 1.7.1
- **tdjson = 1.7.3**

ok tanks, so i am building tdjson version 1.7.1
maybe I use TD 1.7.0, which version is more stable?

**Comment by fewensa** [comment]
You should be use v1.7.0, 
https://github.com/tdlib/td/releases/tag/v1.7.0

All 1.7.x (telegram-client/rtdlib) versions are bound to td@v1.7.0

**Comment by fewensa** [comment]
You can try it, if you still have problems, please reopen issue

**Comment by ehsansafari** [comment]
I used version 1.7.0 but it is still a problem
like this:

![2021-09-09 17_47_36-](https://user-images.githubusercontent.com/19387708/132693593-b45718cc-c9b2-4894-82b9-dce141489d49.png)

![2021-09-09 17_39_19-ehsan@ESI_ ~_rustBot_bot](https://user-images.githubusercontent.com/19387708/132693625-39eccb48-a401-40f9-bfd8-72c0fc539c2b.png)

![2021-09-09 17_44_31-](https://user-images.githubusercontent.com/19387708/132693639-2b89150b-587c-40d7-97be-f3ca08a244f3.png)

**Comment by fewensa** [comment]
No, the version of tdjson you are using is 1.7.7 

![image](https://user-images.githubusercontent.com/37804932/132698633-c6e888a0-f530-4004-bed6-a289abe24c45.png)

you can use listen update option to read this value.
https://github.com/fewensa/telegram-client/blob/7dfad7c7c7e901a4117f88353dcf92fbdc717cd5/examples/client_event.rs#L63

Two suggestions

1. Change your libtdjson dylib use 1.7.0
2. Use telegram-client/rtdlib 0.7.x, (this version bound td master branch. but td update is very fast, there may be other problems )


Related:
https://github.com/tdlib/td/issues/1419

**Comment by ehsansafari** [comment]
So i maked https://github.com/tdlib/td/releases/tag/v1.7.0
but it is libtdjson.so.1.7.7 rolling version of [TD-tag/v1.7.0](https://github.com/tdlib/td/releases/tag/v1.7.0)
so which TD-tag makes rolling libtdjson version 1.7.0?

**Comment by fewensa** [comment]
Maybe 1.7.7 will be generated when a certain step is wrong? check it and try again. I don't think it should be like this.

also, you can read this issue
https://github.com/fewensa/telegram-client/issues/6

now you can get lib from this repository https://github.com/dorak88783/tdlib-builder


In my plan, there will be automatic ci to compile these dependencies in the future

**Comment by fewensa** [comment]
```bash
sudo apt-get -qq update > /dev/null
sudo apt-get -qq upgrade > /dev/null
sudo apt-get -qq install make git zlib1g-dev libssl-dev gperf php-cli cmake g++  > /dev/null
git clone https://github.com/tdlib/td.git
cd td
git checkout v1.7.0
rm -rf build
mkdir build

cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../tdlib ..
cmake --build . --target install
ls ../tdlib/lib/*libtdjson.so*
```

Try this?

> Copy from https://github.com/dorak88783/tdlib-builder/blob/main/.github/workflows/build.yml 
> Add `git checkout v1.7.0`

**Comment by fewensa** [comment]
In addition, please check how your project depends on libtdjson

**Comment by ehsansafari** [comment]
I maked whit `git checkout v1.7.0`
but 
![2021-09-09 22_13_05-Settings](https://user-images.githubusercontent.com/19387708/132736497-95ba5d95-42dd-4583-bae9-b748dc5fffc9.png)

> In addition, please check how your project depends on libtdjson
>> I copy the fileslibtdjson.so&libtdjson.so1.7.0 to the /usr/lib/x86_64-linux-gnu/

this error https://github.com/fewensa/telegram-client/issues/28#issue-990960799 from TDLib or telegram-client , rtdlib ?
I think I should read your source telegram-client, rtdlib code to find the main bugs and we will probably need to upgrade to 1.7.7 for support full

**Comment by fewensa** [comment]
You need to delete the data folder by your set. 
https://github.com/fewensa/telegram-client/blob/7dfad7c7c7e901a4117f88353dcf92fbdc717cd5/examples/client_event.rs#L75
The reason is this data write uses 1.7.7,
1.7.0 does not support 1.7.7 data.
please use 1.7.0 create again.

**Comment by ehsansafari** [comment]
before sending the https://github.com/fewensa/telegram-client/issues/28#issuecomment-916318743, I thought I should delete the data, but I got tired of compiling the TD and did not try😂🤦‍♂️.

**I tried it, so rolling 1.7.0 of the v1.7.0 tag works and has no errors**
Thank you
so I just needed the `git checkout v1.7.0` command.
Now this https://github.com/fewensa/telegram-client/issues/27 remains, which I will research tomorrow
