### ISSUE TITLE
A new telegram client update

### ISSUE THREAD

**Issue by hh-h** [fewensa/telegram-client#29]
Recently telegram team updated the protocol and my application doesn't work anymore.
I used telegram-client = "1.7.0" and rtdlib = "1.7.4"
What versions should I use now to fix it? Thanks

`[ 2][t 4][1638793389.891224145][NetQueryDelayer.cpp:72][#1][!NetQueryDelayer]   Failed: [Query:[id:262144][tl:0x03173d78][state:Query]] [timeout:333.000000][total_timeout:333.000000] because of [Error : 420 : FLOOD_WAIT_333] from Session:2:main::Connect::Tcp::[149.154.167.50:443] to DcId{2} from [172.17.0.7:39600]`

related
https://github.com/tdlib/td/issues/1758
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1833245.html

**Comment by fewensa** [comment]
Thanks for your report! @hh-h

I think you can try build td with master branch. then replace `so` file directly. (In this way, maybe have some error for api)

Or you can use 0.7.x https://crates.io/crates/telegram-client/0.7.1  this version is bind with td master branch
 but is published three month ago, I'm not sure itzs works. 

So I will update this crate as soon the version is 0.7.2

**Comment by hh-h** [comment]
Looking forward to 0.7.2, thank you!

**Comment by fewensa** [comment]
- rtdlib@v0.7.2
   - https://github.com/fewensa/rtdlib/releases/tag/v0.7.2
   - https://crates.io/crates/rtdlib/0.7.2

- telegram@v0.7.2
   - https://github.com/fewensa/telegram-client/commit/535cc6e9df343bff3898646af5560a6e8de7987e
   - https://github.com/fewensa/telegram-client/commit/4dc7c9e9666f7212744287be0b53d276b7ae2794
   - https://github.com/fewensa/telegram-client/releases/tag/v0.7.2
   - https://crates.io/crates/telegram-client/0.7.2

Bind tdlib commit is https://github.com/tdlib/td/commit/858078d89fcd2ad1d9860547e3f87c49d0f9abe9

The README is already updated. please read it. and choose the correct version.

https://github.com/fewensa/telegram-client#td-and-rtdlibtelegram-client

It's tested in my local machine correct works. If you have more questions you can reopen this issue or create a new issue.

About the new version in create.io please wait some minutes. the rtdlib crate must publish first. I'll update there when all published

**Comment by fewensa** [comment]
https://crates.io/crates/rtdlib/0.7.2
https://crates.io/crates/telegram-client/0.7.2

All done.
Please use same version of td to compile. https://github.com/tdlib/td/commit/858078d89fcd2ad1d9860547e3f87c49d0f9abe9

**Comment by mckaygerhard** [comment]
related to telegramdesktop/tdesktop#17330, telegramdesktop/tdesktop#17328 ars3niy/tdlib-purple#120

**Comment by hh-h** [comment]
Thanks @fewensa it works again!
Built with **rtdlib@0.7.2**, **telegram-client@0.7.2**, and **libtdjson@1.7.9** from the master branch
