### ISSUE TITLE
TELEGRAM DATA FAIL

### ISSUE THREAD

**Issue by modestmicha** [fewensa/telegram-client#31]
```
SerdeJson(Error("updateSupergroup can't deserialize to TdType::UpdateSupergroup; Error(\"missing field `is_broadcast_group`\", line: 0, column: 0)", line: 0, column: 0))
SerdeJson(Error("updateNewChat can't deserialize to TdType::UpdateNewChat; Error(\"missing field `has_protected_content`\", line: 0, column: 0)", line: 0, column: 0))
SerdeJson(Error("updateChatLastMessage can't deserialize to TdType::UpdateChatLastMessage; Error(\"missing field `sender_id`\", line: 0, column: 0)", line: 0, column: 0))
SerdeJson(Error("updateUser can't deserialize to TdType::UpdateUser; Error(\"missing field `is_fake`\", line: 0, column: 0)", line: 0, column: 0))
```

I'm on the latest version. Everything used to work fine. Now I get the errors above. Any idea where to best fix this?

**Comment by modestmicha** [comment]
`SerdeJson(Error("updateSupergroupFullInfo can't deserialize to TdType::UpdateSupergroupFullInfo; Error(\"invalid type: string \\\"\\\", expected struct ChatInviteLink\", line: 0, column: 0)", line: 0, column: 0))`

**Comment by fewensa** [comment]
> the latest version.

What's version about telegram-client/rtdlib/td ?

**Comment by modestmicha** [comment]
telegram-client 0.8.0
rtdlib 0.8.0
td 1.7.0
I guess I'm not using the latest version of td which is 1.8

**Comment by fewensa** [comment]
Yes, I think so. please read this.
https://github.com/fewensa/telegram-client#version

If you use 0.8.0 of telegram-client/rtdlib you should compile td use commit https://github.com/tdlib/td/commit/fa8feefed70d64271945e9d5fd010b957d93c8cd

If you use 1.8.0 you should compile td https://github.com/tdlib/td/releases/tag/v1.8.0

**Comment by modestmicha** [comment]
After installing td with tag 1.8.0 from source I still get the following error:
`SerdeJson(Error("updateChatThemes can't deserialize to TdType::UpdateChatThemes; Error(\"invalid type: string \\\"5784882925472317444\\\", expected isize\", line: 0, column: 0)", line: 0, column: 0))`

Not sure if the error is still on my side or if this is a change that was not covered. Just in case I created a PR against rtdlib.

**Comment by fewensa** [comment]
Fixed this issue. please use 1.8.1 or 0.8.1 (Please compile td use commit https://github.com/tdlib/td/commit/789b9c0a554d779945db027fd2612909c676345f)

**Comment by fewensa** [comment]
About the version chosen you can read https://github.com/fewensa/telegram-client/blob/master/version.md
