### ISSUE TITLE
build fail in mac

### ISSUE THREAD

**Issue by tingfeng-key** [fewensa/telegram-client#7]
build fail in mac.
tip:
```
   Compiling proc-macro2 v1.0.4
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.5
   Compiling ryu v1.0.0
   Compiling serde v1.0.101
   Compiling libc v0.2.62
   Compiling log v0.4.8
   Compiling itoa v0.4.4
   Compiling cfg-if v0.1.10
   Compiling telegram-client v1.4.0
   Compiling quote v1.0.2
   Compiling daemon v0.0.8
   Compiling serde_derive v1.0.101
   Compiling serde_json v1.0.40
   Compiling rtdlib v1.4.0
error[E0599]: no method named `run` found for type `daemon::daemon::Daemon` in the current scope
   --> /Users/wzl/.cargo/registry/src/code.aliyun.com-738b7dba08a2a41e/telegram-client-1.4.0/src/client.rs:140:12
    |
140 |     daemon.run(move |rx: Receiver<State>| {
    |            ^^^ method not found in `daemon::daemon::Daemon`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `telegram-client`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by fewensa** [comment]
Thanks you for sharing the issue @tingfeng-key 


Because use [daemon](https://crates.io/crates/daemon) crate, and I not use macos, so I unchecked usage of macos. 

I found that  https://github.com/bozaro/daemon-rs/blob/master/src/lib.rs  This crate only support `windows` and `linux`

Maybe there will change to use thread

**Comment by fewensa** [comment]
The new version fix it.

https://github.com/fewensa/telegram-client/releases/tag/1.3.1
https://github.com/fewensa/telegram-client/releases/tag/1.4.1

And it already pushed to crate.io
Try it and feedback any question.

**Comment by tingfeng-key** [comment]
i use the last version to build, tips:
```

  = note: ld: warning: directory not found for option '-L./lib'
          ld: library not found for -ltdjson
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

```

**Comment by fewensa** [comment]
this crate dependence [td](https://github.com/tdlib/td#building), so you need add libtdjson.so to dependency.

If you use macos, see that [Installing dependencies](https://github.com/tdlib/td#installing-dependencies)  to build `libtdjson.so` for macos, and then [How include libtdjson.so](https://github.com/fewensa/rtdlib#how-include-libtdjsonso)

Currently telegram-client crate does not provide dynamic link library, But this is within the plan
https://github.com/fewensa/telegram-client/issues/6

So now you have to compile, you need to compile td yourself to get the so file and then add to the dependency

**Comment by tingfeng-key** [comment]
good , i trying build libtdjson ,thank
